#!/usr/bin/env bash
#
# bootstrap installs things.

cd "$(dirname "$0")/.."
DOTFILES_ROOT=$(pwd)

set -e

echo ''

info () {
  printf "  [ \033[00;34m..\033[0m ] $1"
}

user () {
  printf "\r  [ \033[0;33m?\033[0m ] $1 "
}

success () {
  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}

fail () {
  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
  echo ''
  exit
}

setup_gitconfig () {
  if ! [ -f git/gitconfig.symlink ]
  then
    info 'setup gitconfig'

    git_credential='cache'
    if [ "$(uname -s)" == "Darwin" ]
    then
      git_credential='osxkeychain'
    fi

    user ' - What is your github author name?'
    read -e git_authorname
    user ' - What is your github author email?'
    read -e git_authoremail

    sed -e "s/AUTHORNAME/$git_authorname/g" -e "s/AUTHOREMAIL/$git_authoremail/g" -e "s/GIT_CREDENTIAL_HELPER/$git_credential/g" git/gitconfig.symlink.example > git/gitconfig.symlink

    success 'gitconfig'
  fi
}

setup_ohmyzsh () {
  if ! [ -d $HOME/.oh-my-zsh ]
  then
    info 'setup oh-my-zsh'
    git clone git://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh 
    success 'oh-my-zsh'
  fi
}

link_file () {
  local src=$1 dst=$2

  local overwrite= backup= skip=
  local action=

  if [ -f "$dst" -o -d "$dst" -o -L "$dst" ]
  then

    if [ "$overwrite_all" == "false" ] && [ "$backup_all" == "false" ] && [ "$skip_all" == "false" ]
    then

      local currentSrc="$(readlink $dst)"

      if [ "$currentSrc" == "$src" ]
      then

        skip=true;

      else

        user "File already exists: $dst ($(basename "$src")), what do you want to do?\n\
        [s]kip, [S]kip all, [o]verwrite, [O]verwrite all, [b]ackup, [B]ackup all?"
        read -n 1 action

        case "$action" in
          o )
            overwrite=true;;
          O )
            overwrite_all=true;;
          b )
            backup=true;;
          B )
            backup_all=true;;
          s )
            skip=true;;
          S )
            skip_all=true;;
          * )
            ;;
        esac

      fi

    fi

    overwrite=${overwrite:-$overwrite_all}
    backup=${backup:-$backup_all}
    skip=${skip:-$skip_all}

    if [ "$overwrite" == "true" ]
    then
      rm -rf "$dst"
      success "removed $dst"
    fi

    if [ "$backup" == "true" ]
    then
      mv "$dst" "${dst}.backup"
      success "moved $dst to ${dst}.backup"
    fi

    if [ "$skip" == "true" ]
    then
      success "skipped $src"
    fi
  fi

  if [ "$skip" != "true" ]  # "false" or empty
  then
    ln -s "$1" "$2"
    success "linked $1 to $2"
  fi
}

install_dotfiles () {
  info 'installing dotfiles'

  local overwrite_all=false backup_all=false skip_all=false

  for src in $(find "$DOTFILES_ROOT" -maxdepth 2 -name '*.symlink')
  do
    dst="$HOME/.$(basename "${src%.*}")"
    link_file "$src" "$dst"
  done
}

setup_vim () {
  info 'installing vundle'
  git clone https://github.com/gmarik/Vundle.vim.git ~/.dotfiles/vim/vim.symlink/bundle/Vundle.vim
  success "vundle installed"
  info 'installing vim plugins'
  vim +PluginInstall +qall
  success "vim plugins now up to date"
}

# Required for other install-Darwin.sh scripts
install_homebrew () {
  info 'install homebrew'
  if ! command -v brew >/dev/null 2>&1
  then
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" > /tmp/homebrew-install.log
    brew doctor
    success 'homebrew installed'
  else
    success 'skipping. homebrew already installed'
  fi
}

install_fish () {
  info 'install fish'
  if ! command -v fish >/dev/null 2>&1
  then
    brew install fish || sudo apt-get install -y fish || sudo yum install -y fish
    success 'fish installed'
  else
    success 'skipping. fish already installed'
  fi
}

setup_fish () {
  info 'setup fish'
  if [ "$(uname)" == "Darwin" ]; then
    if [[ "$(dscl . -read /Users/chanjoe UserShell)" =~ fish ]]; then
    fi
  fi
  if ! command -v fish >/dev/null 2>&1
  then
    brew install fish || sudo apt-get install -y fish || sudo yum install -y fish
    success 'fish installed'
  else
    success 'skipping. fish already installed'
  fi
}

# Must be first
if [ "$(uname)" == "Darwin" ]; then
  install_homebrew
fi
# If no args given run interactive stuff
if [ $# -eq 0 ]; then
    setup_gitconfig
fi
setup_ohmyzsh
install_dotfiles
setup_vim
install_fish

echo ''
echo '  All installed!'
