#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname $0)"/..

# find the OS specific (Darwin|Linux) installers and run them iteratively
echo "  Running */install-$(uname).sh"
find . -name install-$(uname).sh | while read installer ; do sh -c "${installer}" ; done
echo "  Running */post-install-$(uname).sh"
find . -name post-install-$(uname).sh | while read installer ; do sh -c "${installer}" ; done

echo "  Running */install.sh"
find . -name install.sh | while read installer ; do sh -c "${installer}" ; done
echo "  Running */post-install.sh"
find . -name post-install.sh | while read installer ; do sh -c "${installer}" ; done

echo "  DONE!"

if [ "$(uname)" == "Darwin" ]; then
  echo "› brew bundle"
  brew bundle
  echo "What's next? How about..."
  echo "* Run osx/set-defaults.sh"
  echo "* Setup iTerm: Load ~/Dropbox/Documents/Application Files/iTerm2/com.googlecode.iterm2.plist in iTerm Preferences->Load peferences from a custom folder or URL->Browse"
  echo "* Install TodoTxtMac: https://github.com/mjdescy/TodoTxtMac/releases"
fi

exit 0
