#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname $0)"/..

if ! command -v brew >/dev/null 2>&1
then
  echo "  Installing Homebrew for you."
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" > /tmp/homebrew-install.log
fi


# find the OS specific (Darwin|Linux) installers and run them iteratively
echo "  Running */install-$(uname).sh"
find . -name install-$(uname).sh | while read installer ; do sh -c "${installer}" ; done
echo "  Running */post-install-$(uname).sh"
find . -name post-install-$(uname).sh | while read installer ; do sh -c "${installer}" ; done

echo "  Running */install.sh"
find . -name install.sh | while read installer ; do sh -c "${installer}" ; done
echo "  Running */post-install.sh"
find . -name post-install.sh | while read installer ; do sh -c "${installer}" ; done

echo "  DONE!"
echo "What's next? How about..."
echo "* Setup iTerm: Load ~/Dropbox/Documents/Application Files/iTerm2/com.googlecode.iterm2.plist in iTerm Preferences->Load peferences from a custom folder or URL->Browse"
echo "* Install these from the Mac App Store:"
echo Evernote
echo Growl
echo Pixelmator
echo Skitch
echo System Lens

exit 0
