#!/usr/bin/env bash
#
# run after bootstrap

cd "$(dirname "$0")/.."
DOTFILES_ROOT=$(pwd)

set -e

echo ''

info () {
  printf "  [ \033[00;34m..\033[0m ] $1"
}

user () {
  printf "\r  [ \033[0;33m?\033[0m ] $1 "
}

success () {
  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}

fail () {
  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
  echo ''
  exit
}

setup_ohmyzsh_theme () {
    info 'install oh-my-zsh custom theme'
    curl -s https://raw.githubusercontent.com/foolishbrilliance/zsh-dotfiles/master/zsh/foolishbrilliance.zsh-theme -o $HOME/.oh-my-zsh/themes/foolishbrilliance.zsh-theme --create-dirs
    success 'oh-my-zsh custom theme'
}

setup_homebrew () {
    info 'install homebrew'
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    brew doctor
    success 'homebrew'
}

setup_zsh () {
    info 'setup zsh'
    brew install zsh
    # Must use `sudo` with `chsh` here because from `man chsh`:
    #     The shell field is the command interpreter the user prefers.  If the
    #     shell field is empty, the Bourne shell, /bin/sh, is assumed.  When alter-
    #     ing a login shell, and not the super-user, the user may not change from a
    #     non-standard shell or to a non-standard shell.  Non-standard is defined
    #     as a shell not found in /etc/shells.
    sudo chsh -s /usr/local/bin/zsh `whoami`
    success 'zsh'
}

setup_ohmyzsh_theme
setup_homebrew
setup_zsh

echo ''
echo '  All installed!'

echo "What's next? How about..."
echo "* Setup iTerm: Load ~/Dropbox/Documents/Application Files/iTerm2/com.googlecode.iterm2.plist in iTerm Preferences->Load peferences from a custom folder or URL->Browse"
